import commutative_rings_defined_combinatorial_properties_theorem_canonical_lane_mathlib.GateLemmas
import commutative_rings_defined_combinatorial_properties_theorem_canonical_lane_mathlib.FinalTheorem
